version: "3"
services:
    geoportail_world:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: geoportail_world
        container_name: geoportail_world
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - ./:/var/www/html
            - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - geoportail_world
        depends_on:
            - geoportail_world_pgsql
            - geoportail_world_meilisearch

    geoportail_world_pgsql:
        restart: always
        build:
            context: .
            dockerfile: .docker/Dockerfile-db
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        container_name: geoportail_world_pgsql
        environment:
            PGPASSWORD: "${PG_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        networks:
            - geoportail_world
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-q",
                    "-d",
                    "${DB_DATABASE}",
                    "-U",
                    "${DB_USERNAME}",
                ]
            retries: 3
            timeout: 5s

    geoportail_world_meilisearch:
        container_name: geoportail_world_meilisearch
        image: getmeili/meilisearch:v0.27.2
        environment:
            - http_proxy
            - https_proxy
            - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
            - MEILI_ENV=${MEILI_ENV:-development}
            - MEILI_LOG_LEVEL
            - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
        ports:
            - ${MEILI_PORT:-7700}:7700
        networks:
            - geoportail_world
        volumes:
            - "geoportail_world_meilisearch:/data.ms"
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--spider",
                    "http://geoportail_world_meilisearch:7700/health",
                ]
            retries: 3
            timeout: 5s
networks:
    geoportail_world:
        driver: bridge
volumes:
    geoportail_world_meilisearch:
        driver: local
