FROM postgres:11-alpine

RUN apt-get update \
    && apt-get install wget -y \
    && apt-get install postgresql-11-postgis-3 -y \
    && apt-get install postgis -y

CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]
